lasso:
  model: Lasso
  params:
    alpha: [0.001, 0.1]
    max_iter: [1000, 5000]

ridge:
  model: Ridge
  params:
    alpha: [0.001, 0.1]
    solver: ["auto", "lsqr"]

xgboost:
  model: XGBRegressor
  params:
    n_estimators: [100, 200]
    max_depth: [3, 5]
    learning_rate: [0.01, 0.1]
    subsample: [0.8, 1.0]
    colsample_bytree: [0.8, 1.0]
    gamma: [0, 0.1]
    reg_alpha: [0, 0.1]
    reg_lambda: [1.0, 1.5]

lstm:
  model: LSTM
  params:
    units: [32, 64]
    dropout: [0.0, 0.2]
    recurrent_dropout: [0.0, 0.2]
    optimizer: ["adam"]
    learning_rate: [0.001, 0.01]
    batch_size: [16, 32]
    epochs: [10]
    bidirectional: [False]
