Lasso:
  model: Lasso
  params:
    alpha: 0.1
    max_iter: 1000
  scores:
    train:
      rmse: 150.0706
      mae: 108.3487
      r2: 0.9939
      adjusted_r2: 0.9937
    val:
      rmse: 168.9235
      mae: 110.6074
      r2: 0.9853
      adjusted_r2: 0.9838
    test:
      rmse: 229.5469
      mae: 173.8347
      r2: 0.9296
      adjusted_r2: 0.9222
Ridge:
  model: Ridge
  params:
    alpha: 0.1
    solver: auto
  scores:
    train:
      rmse: 150.124
      mae: 108.4583
      r2: 0.9939
      adjusted_r2: 0.9937
    val:
      rmse: 168.7533
      mae: 110.3669
      r2: 0.9854
      adjusted_r2: 0.9838
    test:
      rmse: 233.185
      mae: 176.9331
      r2: 0.9274
      adjusted_r2: 0.9197
XGBRegressor:
  model: XGBRegressor
  params:
    n_estimators: 200
    max_depth: 3
    learning_rate: 0.1
    subsample: 1.0
    colsample_bytree: 1.0
    gamma: 0
    reg_alpha: 0.1
    reg_lambda: 1.5
  scores:
    train:
      rmse: 81.218
      mae: 62.0462
      r2: 0.9982
      adjusted_r2: 0.9981
    val:
      rmse: 81.6197
      mae: 63.15
      r2: 0.9966
      adjusted_r2: 0.9962
    test:
      rmse: 1059.0695
      mae: 888.9811
      r2: -0.4984
      adjusted_r2: -0.6561
