Lasso:
  model: Lasso
  params:
    alpha: 0.1
    max_iter: 1000
  scores:
    train:
      rmse: 150.253
      mae: 108.4419
      r2: 0.9938
      adjusted_r2: 0.9936
    val:
      rmse: 168.9851
      mae: 110.551
      r2: 0.9844
      adjusted_r2: 0.9827
    test:
      rmse: 227.4089
      mae: 171.0028
      r2: 0.9304
      adjusted_r2: 0.923
Ridge:
  model: Ridge
  params:
    alpha: 0.1
    solver: auto
  scores:
    train:
      rmse: 150.304
      mae: 108.5555
      r2: 0.9938
      adjusted_r2: 0.9936
    val:
      rmse: 168.8238
      mae: 110.3332
      r2: 0.9844
      adjusted_r2: 0.9828
    test:
      rmse: 230.7329
      mae: 173.7586
      r2: 0.9283
      adjusted_r2: 0.9208
XGBRegressor:
  model: XGBRegressor
  params:
    n_estimators: 200
    max_depth: 3
    learning_rate: 0.1
    subsample: 1.0
    colsample_bytree: 0.8
    gamma: 0
    reg_alpha: 0
    reg_lambda: 1.5
  scores:
    train:
      rmse: 83.175
      mae: 63.5938
      r2: 0.9981
      adjusted_r2: 0.998
    val:
      rmse: 81.7636
      mae: 63.1915
      r2: 0.9963
      adjusted_r2: 0.996
    test:
      rmse: 1177.5956
      mae: 989.7264
      r2: -0.8665
      adjusted_r2: -1.0639
