Lasso:
  model: Lasso
  params:
    alpha: 0.1
    max_iter: 1000
  scores:
    train:
      rmse: 150.3746
      mae: 108.4988
      r2: 0.9938
      adjusted_r2: 0.9936
    val:
      rmse: 168.852
      mae: 110.3876
      r2: 0.984
      adjusted_r2: 0.9823
    test:
      rmse: 225.4317
      mae: 169.2169
      r2: 0.9312
      adjusted_r2: 0.924
Ridge:
  model: Ridge
  params:
    alpha: 0.1
    solver: lsqr
  scores:
    train:
      rmse: 150.4337
      mae: 108.608
      r2: 0.9938
      adjusted_r2: 0.9936
    val:
      rmse: 168.658
      mae: 110.1098
      r2: 0.9841
      adjusted_r2: 0.9824
    test:
      rmse: 228.0654
      mae: 171.3416
      r2: 0.9296
      adjusted_r2: 0.9222
XGBRegressor:
  model: XGBRegressor
  params:
    n_estimators: 200
    max_depth: 3
    learning_rate: 0.1
    subsample: 1.0
    colsample_bytree: 1.0
    gamma: 0
    reg_alpha: 0.1
    reg_lambda: 1.5
  scores:
    train:
      rmse: 80.1354
      mae: 61.4207
      r2: 0.9982
      adjusted_r2: 0.9982
    val:
      rmse: 77.833
      mae: 59.3049
      r2: 0.9966
      adjusted_r2: 0.9962
    test:
      rmse: 1329.0998
      mae: 1137.3368
      r2: -1.391
      adjusted_r2: -1.6427
