Lasso:
  model: Lasso
  params:
    alpha: 0.1
    max_iter: 1000
  scores:
    train:
      rmse: 149.9877
      mae: 108.4071
      r2: 0.994
      adjusted_r2: 0.9938
    val:
      rmse: 167.8772
      mae: 108.9706
      r2: 0.9867
      adjusted_r2: 0.9853
    test:
      rmse: 230.742
      mae: 176.1227
      r2: 0.9313
      adjusted_r2: 0.9241
Ridge:
  model: Ridge
  params:
    alpha: 0.1
    solver: auto
  scores:
    train:
      rmse: 150.0368
      mae: 108.5204
      r2: 0.994
      adjusted_r2: 0.9938
    val:
      rmse: 167.7172
      mae: 108.7445
      r2: 0.9867
      adjusted_r2: 0.9853
    test:
      rmse: 234.3581
      mae: 179.2852
      r2: 0.9292
      adjusted_r2: 0.9217
XGBRegressor:
  model: XGBRegressor
  params:
    n_estimators: 100
    max_depth: 3
    learning_rate: 0.1
    subsample: 1.0
    colsample_bytree: 1.0
    gamma: 0
    reg_alpha: 0
    reg_lambda: 1.0
  scores:
    train:
      rmse: 103.8246
      mae: 78.9337
      r2: 0.9971
      adjusted_r2: 0.997
    val:
      rmse: 101.7037
      mae: 76.627
      r2: 0.9951
      adjusted_r2: 0.9946
    test:
      rmse: 822.7881
      mae: 666.3354
      r2: 0.1269
      adjusted_r2: 0.0354
